
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class UjiKebolehan extends javax.swing.JFrame {
    String temp = "";
    Double ti, bt, h1;
    /**
     * Creates new form UjiKebolehan
     */
    public UjiKebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();
        hasil1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tbKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfberat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btCoba = new javax.swing.JButton();
        btHitung = new javax.swing.JButton();
        tfBIdeal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel9.setText("Kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 140, 20, 20);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jRadioButton2.setText("Laki-laki");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(270, 180, 93, 23);

        jLabel6.setFont(new java.awt.Font("Swis721 Hv BT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Hasil Diagnosa Kesehatan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 320, 210, 15);

        jLabel7.setText("Cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 110, 20, 20);

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel4.setText("CEK IDEAL TUBUH");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 20, 160, 30);

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });
        jPanel1.add(tfnama);
        tfnama.setBounds(160, 60, 100, 30);
        jPanel1.add(tfTinggi);
        tfTinggi.setBounds(160, 100, 50, 30);
        jPanel1.add(hasil2);
        hasil2.setBounds(50, 380, 390, 30);
        jPanel1.add(hasil1);
        hasil1.setBounds(50, 340, 390, 30);

        jLabel10.setText("Berat Badan Ideal Anda Adalah ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 280, 180, 14);

        tbKeluar.setText("Keluar");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(tbKeluar);
        tbKeluar.setBounds(340, 220, 80, 30);

        jLabel1.setText("Nama :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 70, 50, 14);
        jPanel1.add(tfberat);
        tfberat.setBounds(160, 140, 50, 30);

        jLabel2.setText("Tinggi :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 110, 50, 14);

        jLabel8.setText("Jenis Kelamin");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 180, 80, 20);

        jRadioButton1.setText("Perempuan");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(160, 180, 100, 23);

        jLabel5.setText("Berat :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 150, 50, 14);

        btCoba.setText("Coba Lagi");
        btCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCobaActionPerformed(evt);
            }
        });
        jPanel1.add(btCoba);
        btCoba.setBounds(210, 220, 90, 30);

        btHitung.setText("Hitung");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btHitung);
        btHitung.setBounds(90, 220, 70, 30);
        jPanel1.add(tfBIdeal);
        tfBIdeal.setBounds(240, 270, 50, 30);

        jLabel3.setText("Kg");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 270, 20, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 440);

        setBounds(0, 0, 526, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void btCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCobaActionPerformed
        // TODO add your handling code here:

        tfnama.setText("");
        tfTinggi.setText("");
        tfberat.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        tfBIdeal.setText("");
        hasil1.setText("");
        hasil2.setText("");
    }//GEN-LAST:event_btCobaActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
        // TODO add your handling code here:
        if (tfberat.getText().equals("")||tfTinggi.getText().equals("")
                ||tfnama.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Kotak isian belum diisi");}
        else if (jRadioButton1.isSelected()||jRadioButton2.isSelected())
            try {
                    Proses();
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null,"Inputkan ada yang salah");
            }else{
          JOptionPane.showMessageDialog(null,"Jenis kelamin Harus Diisi");
    }
    }//GEN-LAST:event_btHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UjiKebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCoba;
    private javax.swing.JButton btHitung;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JTextField tfBIdeal;
    private javax.swing.JTextField tfTinggi;
    private javax.swing.JTextField tfberat;
    private javax.swing.JTextField tfnama;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tfTinggi.getText());
        bt = Double.valueOf(tfberat.getText());
        
        if (jRadioButton1.isSelected()){
            h1 = (ti - 110) * 1;
        } else if (jRadioButton2.isSelected()){
            h1 = (ti - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1 < bt){
        tfBIdeal.setText(temp);
        hasil1.setText("Maaf " + tfnama.getText() + " , Sepertinya anda Overweight :(");
        hasil2.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        }else if (h1 > bt){
        tfBIdeal.setText(temp);
        hasil1.setText("Maaf " + tfnama.getText() + " , Sepertinya anda Undderweight : ( ");
        hasil2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else{
        tfBIdeal.setText(temp);
        hasil1.setText("Hallo " + tfnama.getText() + " , Berat badan anda sudah ideal :) ");
        hasil2.setText("Lanjutkan pola makan teratur dan gaya hdup sehat :) ");
        }
    }
}
